#!/usr/bin/env bash
xrandr --output HDMI-1 --off --output eDP-1 --primary --mode 3840x2160 --scale 1x1 --pos 0x0 --rotate normal
#xrandr --setmonitor eDP-1-1 1920/172x1080/98+0+0 eDP-1
xrandr --setmonitor eDP-1-2 1920/172x1080/98+0+1081 eDP-1
xrandr --setmonitor eDP-1-3 1920/172x1080/98+960+0 none
xrandr --setmonitor eDP-1-4 1920/172x1080/98+1921+1081 none
# xrandr --fb 1920x1080
# xrandr --fb 1921x1080
feh --bg-fill $(find ~/Pictures/Wallpaper/bingimage/ -type f | shuf -n 1)
